name: Test API Module

on:
  push:
    paths:
      - 'tests/api/test_api.py'
      - 'tests/api/**'
  pull_request:
    paths:
      - 'tests/api/test_api.py'
      - 'tests/api/**'
  workflow_dispatch:  # ручной запуск

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install pytest requests pytest-httpx \
          webdriver-manager selenium

    - name: Run API tests
      run: |
        pytest -s -v \
          tests/api/test_api.py \
          --junitxml=junit/test-results.xml 
          --log-cli-level=INFO \
          --log-file=logs/test_api.log \
          -o log_cli=true

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          logs/test_api.log
          junit/test-results.xml
